export const LOG_IN : String = 'LOG_IN';
export const LOG_OUT : String = 'LOG_OUT';
export const LOG_IN_ERROR : String = 'LOG_OUT';
export const AUTH_FETCH_NOT_REQUIRED = 'AUTH_FETCH_NOT_REQUIRED'

export const SUBSCRIBE: String = 'SUBSCRIBE';
export const UNSUBSCRIBE: String = 'UNSUBSCRIBE';
export const FILL_PERSONAL_DATA: String = 'FILL_PERSONAL_DATA';
export const FILL_BONDMANS: String = 'FILL_BONDMANS';
export const FILL_JOBSEEKER_NAME: String = 'FILL_JOBSEEKER_NAME';
export const FILL_JOBSEEKER_BIRTHDAY: String = 'FILL_JOBSEEKER_BIRTDAY';
export const RESET_PERSONAL_DATA: String = "RESET_PERSONAL_DATA"
export const UPDATE_AVATAR_URL_UID: String = "UPDATE_URL_UID"

export const SET_FILTER : String = 'SET_FILTER';
export const SET_PAGINATION : String = 'SET_PAGINATION';

export const START_LOADING : String = 'START_LOADING'
export const STOP_LOADING : String = 'STOP_LOADING'

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const OPEN_CHAT = "OPEN_CHAT";
export const HIDE_CHAT = "HIDE_CHAT";

export const ADD_NOTIFICATIONS = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS"
export const AUTH_COMPLETED = "AUTH_COMPLETED"

export const WEBSOCKET_ERROR = "WEBSOCKET_ERROR"

export const SETTINGS = 'SETTINGS'
export const SET_CHATS = 'SET_CHATS'
export const ADD_CHAT = 'ADD_CHAT'
export const REMOVE_CHAT = 'REMOVE_CHAT'
export const ADD_UNREAD_CHAT = "ADD_UNREAD_CHAT"
export const RESET_UNREAD_MESSAGES = "RESET_UNREAD_MESSAGES"

export const SET_CHAT_LAST_MSG_DATE = "SET_CHAT_LAST_MSG_DATE"
export const SET_OPEN_CHAT_ID = "SET_OPEN_CHAT_ID"

export const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION"
export const REMOVE_SUBSCRIPTION = "REMOVE_SUBSCRIPTION"